### ISSUE TITLE
windows anacoda installation conflict with other packages

### ISSUE THREAD

**Issue by Yufei419** [jjstickel/scikit-datasmooth#5]
When I tried to install the windows release for anaconda using 
conda install -c danielng scikits.datasmooth 

I've got a error message says:
UnsatisfiableError: The following specifications were found to be in conflict:
  - scikits.datasmooth
  - toolz

an incomplete list of other packages to be in conflict:
zict
clswriter
xlrd
xlwings
xlwt
werkzeug
wedgetsnbextension
sqlalchemy
sympy
tblib
toolz

Any suggestions on how to fix this?

**Comment by jjstickel** [comment]
I don't use Anaconda, and so I really have no idea. If you have a lot of packages in conflict, maybe something is wrong with your Anaconda installation?
